# Cuppino Product Database - Swedish Label Information
# All products with Swedish compliance data for label printing

products:
    # ===== HONEY PRODUCTS - Apicoltura Bianco =====

    AB-ACACIA-50:
        name_sv: 'Akaciahonung'
        name_it: 'Miele di Acacia'
        weight: '50g'
        label_type: 'qr'
        batch: 'AB-ACACIA-5001'
        ingredients_sv: '100% Akaciahonung'
        allergens_sv: 'Inga kända allergener'
        nutrition:
            energy_kj: '1340'
            energy_kcal: '320'
            fat: '0g'
            carbs: '82g'
            carbs_sugars: '82g'
            protein: '0,2g'
            salt: '0,01g'
        storage_sv: 'Förvaras svalt och torrt, skyddad från ljus'
        storage_it: 'Conservare in luogo fresco e asciutto al riparo da luce e fonti di calore'
        disposal_sv: 'Återvinning: aluminiumlock, ofärgat glas'
        disposal_it: 'Raccolta differenziata: tappo alluminio, vetro trasparente non colorato'
        best_before: '30/06/2028'
        origin: 'Italien (Abruzzo, Guardiagrele)'
        producer: 'Apicoltura Bianco - Italien'
        importer: 'GGMR AB (Cuppino) - info@cuppino.se'
        qr_url: 'https://cuppino.it/products/italian-acacia-honey?variant=52781821395271'

    AB-ACACIA-250:
        name_sv: 'Akaciahonung'
        name_it: 'Miele di Acacia'
        weight: '250g'
        label_type: 'qr'
        batch: 'AB-ACACIA-5701'
        ingredients_sv: '100% Akaciahonung'
        allergens_sv: 'Inga kända allergener'
        nutrition:
            energy_kj: '1340'
            energy_kcal: '320'
            fat: '0g'
            carbs: '82g'
            carbs_sugars: '82g'
            protein: '0,2g'
            salt: '0,01g'
        storage_sv: 'Förvaras svalt och torrt, skyddad från ljus'
        storage_it: 'Conservare in luogo fresco e asciutto al riparo da luce e fonti di calore'
        disposal_sv: 'Återvinning: aluminiumlock, ofärgat glas'
        disposal_it: 'Raccolta differenziata: tappo alluminio, vetro trasparente non colorato'
        best_before: '30/06/2028'
        origin: 'Italien (Abruzzo, Guardiagrele)'
        producer: 'Apicoltura Bianco - Italien'
        importer: 'GGMR AB (Cuppino) - info@cuppino.se'
        qr_url: 'https://cuppino.it/products/italian-acacia-honey?variant=52650721935687'

    AB-ACACIA-500:
        name_sv: 'Akaciahonung'
        name_it: 'Miele di Acacia'
        weight: '500g'
        label_type: 'qr'
        batch: 'AB-ACACIA-6401'
        ingredients_sv: '100% Akaciahonung'
        allergens_sv: 'Inga kända allergener'
        nutrition:
            energy_kj: '1340'
            energy_kcal: '320'
            fat: '0g'
            carbs: '82g'
            carbs_sugars: '82g'
            protein: '0,2g'
            salt: '0,01g'
        storage_sv: 'Förvaras svalt och torrt, skyddad från ljus'
        storage_it: 'Conservare in luogo fresco e asciutto al riparo da luce e fonti di calore'
        disposal_sv: 'Återvinning: aluminiumlock, ofärgat glas'
        disposal_it: 'Raccolta differenziata: tappo alluminio, vetro trasparente non colorato'
        best_before: '30/06/2028'
        origin: 'Italien (Abruzzo, Guardiagrele)'
        producer: 'Apicoltura Bianco - Italien'
        importer: 'GGMR AB (Cuppino) - info@cuppino.se'
        qr_url: 'https://cuppino.it/products/italian-acacia-honey?variant=52779196940615'

    AB-MILLEFIORI-50:
        name_sv: 'Millefiorihonung'
        name_it: 'Miele Millefiori'
        weight: '50g'
        label_type: 'qr'
        batch: 'AB-MILLEFIORI-5001'
        ingredients_sv: '100% Millefiorihonung (Blandblomsterhonung)'
        allergens_sv: 'Inga kända allergener'
        nutrition:
            energy_kj: '1340'
            energy_kcal: '320'
            fat: '0g'
            carbs: '82g'
            carbs_sugars: '82g'
            protein: '0,2g'
            salt: '0,01g'
        storage_sv: 'Förvaras svalt och torrt, skyddad från ljus'
        storage_it: 'Conservare in luogo fresco e asciutto al riparo da luce e fonti di calore'
        disposal_sv: 'Återvinning: aluminiumlock, ofärgat glas'
        disposal_it: 'Raccolta differenziata: tappo alluminio, vetro trasparente non colorato'
        best_before: '30/06/2028'
        origin: 'Italien (Abruzzo, Guardiagrele)'
        producer: 'Apicoltura Bianco - Italien'
        importer: 'GGMR AB (Cuppino) - info@cuppino.se'
        qr_url: 'https://cuppino.it/products/italian-wildflower-honey?variant=52782590492999'

    AB-MILLEFIORI-250:
        name_sv: 'Millefiorihonung'
        name_it: 'Miele Millefiori'
        weight: '250g'
        label_type: 'qr'
        batch: 'AB-MILLEFIORI-5701'
        ingredients_sv: '100% Millefiorihonung (Blandblomsterhonung)'
        allergens_sv: 'Inga kända allergener'
        nutrition:
            energy_kj: '1340'
            energy_kcal: '320'
            fat: '0g'
            carbs: '82g'
            carbs_sugars: '82g'
            protein: '0,2g'
            salt: '0,01g'
        storage_sv: 'Förvaras svalt och torrt, skyddad från ljus'
        storage_it: 'Conservare in luogo fresco e asciutto al riparo da luce e fonti di calore'
        disposal_sv: 'Återvinning: aluminiumlock, ofärgat glas'
        disposal_it: 'Raccolta differenziata: tappo alluminio, vetro trasparente non colorato'
        best_before: '30/06/2028'
        origin: 'Italien (Abruzzo, Guardiagrele)'
        producer: 'Apicoltura Bianco - Italien'
        importer: 'GGMR AB (Cuppino) - info@cuppino.se'
        qr_url: 'https://cuppino.it/products/italian-wildflower-honey?variant=52650722132295'

    AB-MELATA-250:
        name_sv: 'Melatahonung'
        name_it: 'Miele di Melata'
        weight: '250g'
        label_type: 'qr'
        batch: 'AB-MELATA-5701'
        ingredients_sv: '100% Melatahonung (Dagghonung)'
        allergens_sv: 'Inga kända allergener'
        nutrition:
            energy_kj: '1340'
            energy_kcal: '320'
            fat: '0g'
            carbs: '82g'
            carbs_sugars: '82g'
            protein: '0,2g'
            salt: '0,01g'
        storage_sv: 'Förvaras svalt och torrt, skyddad från ljus'
        storage_it: 'Conservare in luogo fresco e asciutto al riparo da luce e fonti di calore'
        disposal_sv: 'Återvinning: aluminiumlock, ofärgat glas'
        disposal_it: 'Raccolta differenziata: tappo alluminio, vetro trasparente non colorato'
        best_before: '30/06/2028'
        origin: 'Italien (Abruzzo, Guardiagrele)'
        producer: 'Apicoltura Bianco - Italien'
        importer: 'GGMR AB (Cuppino) - info@cuppino.se'
        qr_url: 'https://cuppino.it/products/italian-honeydew-honey'

    AB-CASTAGNO-250:
        name_sv: 'Kastanjehonung'
        name_it: 'Miele di Castagno'
        weight: '250g'
        label_type: 'qr'
        batch: 'AB-CASTAGNO-5701'
        ingredients_sv: '100% Kastanjehonung'
        allergens_sv: 'Inga kända allergener'
        nutrition:
            energy_kj: '1340'
            energy_kcal: '320'
            fat: '0g'
            carbs: '82g'
            carbs_sugars: '82g'
            protein: '0,2g'
            salt: '0,01g'
        storage_sv: 'Förvaras svalt och torrt, skyddad från ljus'
        storage_it: 'Conservare in luogo fresco e asciutto al riparo da luce e fonti di calore'
        disposal_sv: 'Återvinning: aluminiumlock, ofärgat glas'
        disposal_it: 'Raccolta differenziata: tappo alluminio, vetro trasparente non colorato'
        best_before: '30/06/2028'
        origin: 'Italien (Abruzzo, Guardiagrele)'
        producer: 'Apicoltura Bianco - Italien'
        importer: 'GGMR AB (Cuppino) - info@cuppino.se'
        qr_url: 'https://cuppino.it/products/italian-chestnut-honey'

    # ===== OLIVE PATE PRODUCTS - Natural =====
    # Note: Ingredient and nutrition information needed from Italian labels

    NAT-907-BLACKOLIVE:
        name_sv: 'Svart Olivkräm'
        name_it: 'Paté di Olive Nere'
        weight: '190g'
        label_type: 'qr'
        ingredients_sv: 'Svarta oliver, extra jungfruolivolja, salt'
        ingredients_it: 'Olive nere, olio extra vergine di oliva, sale'
        allergens_sv: 'Inga kända allergener'
        nutrition:
            energy_kj: '366'
            energy_kcal: '1530'
            fat: '29,8 g'
            fat_saturated: '4,6 g'
            carbs: '22,3 g'
            carbs_sugars: '<0,5 g'
            protein: '2,1 g'
            salt: '2,8 g'
        storage_sv: 'Förvaras svalt och torrt, skyddad från ljus och värmekällor'
        storage_it: 'Conservare in luogo fresco e asciutto al riparo da luce e fonti di calore'
        disposal_sv: 'Återvinning: aluminiumlock, ofärgat glas'
        disposal_it: 'Raccolta differenziata: tappo alluminio, vetro trasparente non colorato'
        best_before: '23/10/2027'
        origin: 'Italien (Abruzzo)'
        producer: 'Natural s.r.l. - Italien'
        importer: 'GGMR AB (Cuppino)'
        qr_url: 'https://cuppino.it/italian-olive-spread-190g-pate-di-olive'

    NAT-908-GREENOLIVE:
        name_sv: 'Grön Olivkräm'
        name_it: 'Paté di Olive Verdi'
        weight: '190g'
        label_type: 'qr'
        ingredients_sv: 'Gröna oliver, extra jungfruolivolja, salt'
        ingredients_it: 'Olive verdi, olio extra vergine di oliva, sale'
        allergens_sv: 'Inga kända allergener'
        nutrition:
            energy_kj: '366'
            energy_kcal: '1530'
            fat: '29,8 g'
            fat_saturated: '4,6 g'
            carbs: '22,3 g'
            carbs_sugars: '<0,5 g'
            protein: '2,1 g'
            salt: '2,8 g'
        storage_sv: 'Förvaras svalt och torrt, skyddad från ljus och värmekällor'
        storage_it: 'Conservare in luogo fresco e asciutto al riparo da luce e fonti di calore'
        disposal_sv: 'Återvinning: aluminiumlock, ofärgat glas'
        disposal_it: 'Raccolta differenziata: tappo alluminio, vetro trasparente non colorato'
        best_before: '23/10/2027'
        origin: 'Italien (Abruzzo)'
        producer: 'Natural s.r.l. - Italien'
        importer: 'GGMR AB (Cuppino)'
        qr_url: 'https://cuppino.it/products/italian-olive-spread-190g-pate-di-olive'

# Common settings
common:
    importer_full: 'GGMR AB (Cuppino), Irisgatan 14, 21565 Malmö - info@cuppino.se'
    label_note_qr: 'Full produktinfo: Skanna QR-koden'
    best_before_text: 'Bäst före:'
    batch_text: 'Partimärkning:'
    net_quantity_text: 'Nettokvantitet:'
    ingredients_text: 'Ingredienser:'
    allergens_text: 'Allergener:'
    nutrition_text: 'Näringsdeklaration per 100g:'
    storage_text: 'Förvaring:'
    origin_text: 'Ursprung:'
    producer_text: 'Producent:'
    importer_text: 'Importör:'
